sudo: required
dist: trusty

before_script: "bundle install"
script:
  - bundle exec rake test_app
  - bundle exec rake spec

addons:
  chrome: stable
  postgresql: 9.4

env:
  - DB=mysql
  - DB=postgres

language: ruby

rvm:
  - 2.5
  - 2.6
  - 2.7

gemfile:
  - gemfiles/spree_3_7.gemfile
  - gemfiles/spree_4_0.gemfile
  - gemfiles/spree_master.gemfile

matrix:
  allow_failures:
    - gemfile: gemfiles/spree_master.gemfile

before_install:
  - mysql -u root -e "GRANT ALL ON *.* TO 'travis'@'%';"
  - wget -N https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
